### ISSUE TITLE
明明是正确的 appId, 返回报错说"SecretId 不存在，请输入正确的密钥"

### ISSUE THREAD

**Issue by renntbenrennt** [MrLiuYS/flutter_tencent_ocr#1]
![image](https://user-images.githubusercontent.com/13610283/78321776-7a47d800-759f-11ea-8fd7-8d830bcff1b7.png)

**Comment by GumplinGo** [comment]
同样的情况，https://ai.qq.com/console/application/  appId是在这里拿到的

**Comment by MrLiuYS** [comment]
https://console.cloud.tencent.com/api/explorer?Product=ocr&Version=2018-11-19&Action=IDCardOCR&SignVersion=

**Comment by MrLiuYS** [comment]
可以试试在腾讯云里面调试一下
https://console.cloud.tencent.com/api/explorer?Product=ocr&Version=2018-11-19&Action=IDCardOCR&SignVersion=

**Comment by MrLiuYS** [comment]
不小心按错.关闭了.可以先试试上面的测试.能不能跑通

**Comment by MrLiuYS** [comment]
SecretId 不是 appId

**Comment by renntbenrennt** [comment]
hello, 你好，谢谢你的回复，不过你能详细说清楚吗？

1. 那个调试的是怎么个调试法？我们都是在ai.qq.com这个地方拿到对应的服务的id的，而且这个也是我们以腾讯ocr为关键字搜出来的东西。
2. 你上面说的SecretId不是appId是什么意思？能不能提供一下具体的说明关于你这个secretId怎么拿到的吗？

thanks in advance.

**Comment by MrLiuYS** [comment]
> hello, 你好，谢谢你的回复，不过你能详细说清楚吗？
> 
> 1. 那个调试的是怎么个调试法？我们都是在ai.qq.com这个地方拿到对应的服务的id的，而且这个也是我们以腾讯ocr为关键字搜出来的东西。
> 2. 你上面说的SecretId不是appId是什么意思？能不能提供一下具体的说明关于你这个secretId怎么拿到的吗？
> 
> thanks in advance.

https://console.cloud.tencent.com/api/explorer?Product=ocr&Version=2018-11-19&Action=IDCardOCR&SignVersion=
打开上面的连接.然后登录.查看秘钥.可以生成出需要的秘钥

![image](https://user-images.githubusercontent.com/13467640/78339832-b3943e00-75c7-11ea-9959-0a59c73ac470.png)

**Comment by MrLiuYS** [comment]
壮士.如果有用.记得给个star.谢谢
